### ISSUE TITLE
ignition-ui todo

### ISSUE THREAD

**Issue by AdrianMrn** [facade/ignition-js#2]
- [x] Move UI code from `ignition` into separate package `ignition-ui`

- [x] Change the css so that classnames won't intersect with classnames on the currently loaded page. Just prefix with `ignition--` or so. We will also have to use [prefixes in tailwind](https://tailwindcss.com/docs/configuration/#prefix). (or use an iframe?)

- [x] An Error shouldn't resolve or show the issue immediately, but only show a small popup at the bottom of the screen. When you click it, a modal should open with the ignition page.
--> How this works technically: flare-client-js should send the Error object to ignition without doing anything else with it, and when you open the page, ignition should send it back to flare-client-js to get the error with all the information, and at the same time ignition should resolve the minified code with the sourcemap.
--> Maybe we could register a `beforeSubmit` function on the FlareClient that stops the report from being sent to Flare, and instead opens it in Ignition? We could also add a `beforeEvaluate` function that accepts the Error and allows returning `false` to stop evaluating the error altogether? This would stop the js thread from halting and slowing the application.
